import Header from '@/components/global/Header';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import GlobalStyle from '@/styles/GlobalStyle';
import Container from '@/components/common/layout/Container';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning={true} className={inter.className}>
        <Header />
        <main>
          <Container>{children}</Container>
        </main>
        <GlobalStyle />
      </body>
    </html>
  );
}
