import Header from '@/components/global/Header';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import GlobalStyle from '@/styles/GlobalStyle';
import Container from '@/components/common/layout/Container';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning={true} className={roboto.className}>
        <Header />
        <main>
          <Container>{children}</Container>
        </main>
        <GlobalStyle />
      </body>
    </html>
  );
}
